# Generated by Django 5.2.4 on 2025-07-21 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='no hay', max_length=254),
        ),
    ]
