# Generated by Django 5.2.4 on 2025-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='endtime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='sin titulo', max_length=70),
            preserve_default=False,
        ),
    ]
